<?php


namespace App\Constants;


class AppConstants
{
    const ROLE_SUPER_ADMIN  = 'super-admin';
    const ROLE_PROJECT_MANAGER  = 'project-manager';

    // Users permission
    const CREATE_USERS  = 'CREATE_USERS';
    const READ_USERS  = 'READ_USERS';
    const UPDATE_USERS  = 'UPDATE_USERS';
    const DELETE_USERS  = 'DELETE_USERS';

    // Roles permission
    const CREATE_ROLES  = 'CREATE_ROLES';
    const READ_ROLES  = 'READ_ROLES';
    const UPDATE_ROLES  = 'UPDATE_ROLES';
    const DELETE_ROLES  = 'DELETE_ROLES';

    // Permissions permission
    const CREATE_PERMISSIONS  = 'CREATE_PERMISSIONS';
    const READ_PERMISSIONS  = 'READ_PERMISSIONS';
    const UPDATE_PERMISSIONS  = 'UPDATE_PERMISSIONS';
    const DELETE_PERMISSIONS  = 'DELETE_PERMISSIONS';

    // Projects permission
    const CREATE_PROJECTS  = 'CREATE_PROJECTS';
    const READ_PROJECTS  = 'READ_PROJECTS';
    const UPDATE_PROJECTS  = 'UPDATE_PROJECTS';
    const DELETE_PROJECTS  = 'DELETE_PROJECTS';
    // Milestones permission
    const CREATE_MILESTONES  = 'CREATE_MILESTONES';
    const READ_MILESTONES  = 'READ_MILESTONES';
    const UPDATE_MILESTONES  = 'UPDATE_MILESTONES';
    const DELETE_MILESTONES  = 'DELETE_MILESTONES';
    // Tasks permission
    const CREATE_TASKS  = 'CREATE_TASKS';
    const READ_TASKS  = 'READ_TASKS';
    const UPDATE_TASKS  = 'UPDATE_TASKS';
    const DELETE_TASKS  = 'DELETE_TASKS';
    // Task types
    const CREATE_TASK_TYPES  = 'CREATE_TASK_TYPES';
    const READ_TASK_TYPES  = 'READ_TASK_TYPES';
    const UPDATE_TASK_TYPES  = 'UPDATE_TASK_TYPES';
    const DELETE_TASK_TYPES  = 'DELETE_TASK_TYPES';
    // Project task categories
    const CREATE_PROJECT_TASK_CATEGORIES  = 'CREATE_PROJECT_TASK_CATEGORIES';
    const READ_PROJECT_TASK_CATEGORIES  = 'READ_PROJECT_TASK_CATEGORIES';
    const UPDATE_PROJECT_TASK_CATEGORIES  = 'UPDATE_PROJECT_TASK_CATEGORIES';
    const DELETE_PROJECT_TASK_CATEGORIES  = 'DELETE_PROJECT_TASK_CATEGORIES';

    // Comments task
    const CREATE_COMMENTS  = 'CREATE_COMMENTS';
    const READ_COMMENTS  = 'READ_COMMENTS';
    const UPDATE_COMMENTS  = 'UPDATE_COMMENTS';
    const DELETE_COMMENTS  = 'DELETE_COMMENTS';
}
